In [30]:
import numpy as np
import math
from scipy import stats
from statsmodels.stats.weightstats import ztest
from scipy.stats import ttest_rel

# Hypothesis tests

In [4]:
data_h0 = np.array([126. , 129.5, 133. , 133. , 136.5, 136.5, 140. , 140. , 140. ,
                140. , 143.5, 143.5, 143.5, 143.5, 143.5, 143.5, 147. , 147. ,
                147. , 147. , 147. , 147. , 147. , 150.5, 150.5, 150.5, 150.5,
                150.5, 150.5, 150.5, 150.5, 154. , 154. , 154. , 154. , 154. ,
                154. , 154. , 154. , 154. , 157.5, 157.5, 157.5, 157.5, 157.5,
                157.5, 157.5, 157.5, 157.5, 157.5, 161. , 161. , 161. , 161. ,
                161. , 161. , 161. , 161. , 161. , 161. , 164.5, 164.5, 164.5,
                164.5, 164.5, 164.5, 164.5, 164.5, 164.5, 168. , 168. , 168. ,
                168. , 168. , 168. , 168. , 168. , 171.5, 171.5, 171.5, 171.5,
                171.5, 171.5, 171.5, 175. , 175. , 175. , 175. , 175. , 175. ,
                178.5, 178.5, 178.5, 178.5, 182. , 182. , 185.5, 185.5, 189., 192.5])

In [5]:
h0_mean = np.mean(data_h0)
h0_mean

159.25

In [7]:
h0_std = np.std(data_h0)
h0_std

13.65

In [8]:
data_h1 = data_h0 * 1.03
data_h1

array([129.78 , 133.385, 136.99 , 136.99 , 140.595, 140.595, 144.2  ,
       144.2  , 144.2  , 144.2  , 147.805, 147.805, 147.805, 147.805,
       147.805, 147.805, 151.41 , 151.41 , 151.41 , 151.41 , 151.41 ,
       151.41 , 151.41 , 155.015, 155.015, 155.015, 155.015, 155.015,
       155.015, 155.015, 155.015, 158.62 , 158.62 , 158.62 , 158.62 ,
       158.62 , 158.62 , 158.62 , 158.62 , 158.62 , 162.225, 162.225,
       162.225, 162.225, 162.225, 162.225, 162.225, 162.225, 162.225,
       162.225, 165.83 , 165.83 , 165.83 , 165.83 , 165.83 , 165.83 ,
       165.83 , 165.83 , 165.83 , 165.83 , 169.435, 169.435, 169.435,
       169.435, 169.435, 169.435, 169.435, 169.435, 169.435, 173.04 ,
       173.04 , 173.04 , 173.04 , 173.04 , 173.04 , 173.04 , 173.04 ,
       176.645, 176.645, 176.645, 176.645, 176.645, 176.645, 176.645,
       180.25 , 180.25 , 180.25 , 180.25 , 180.25 , 180.25 , 183.855,
       183.855, 183.855, 183.855, 187.46 , 187.46 , 191.065, 191.065,
       194.67 , 198.

In [9]:
h1_mean = np.mean(data_h1)
h1_mean

164.0275

In [10]:
h1_std = np.std(data_h1)
h1_std

14.0595

In [11]:
alpha = 0.05

## Z hypothesis test

- $ Z = \frac{\overline{X} - \mu_{0}}{\frac{\sigma}{\sqrt{n}}} $

Manual approch

In [19]:
def z_test(h0, h1):
    h0_mean = np.mean(h0)
    h1_mean = np.mean(h1)
    h1_std = np.std(h1)
    h1_n = len(h1)

    z = (h1_mean - h0_mean) / (h1_std / math.sqrt(h1_n))

    return stats.norm.cdf(z)

In [20]:
z_test(data_h0, data_h1)

0.9996606701617486

In [22]:
p = 1 - z_test(data_h0, data_h1)

if p < alpha:
    print('Reject null hypothesis (H0)')
    print('Accepting alternative hypothesis (H1)')
else:
    print('Reject alternative hypothesis (H1)')
    print('Continuing with null hypothesis (H0)')

Reject null hypothesis (H0)
Accepting alternative hypothesis (H1)


Using statsmodels library

- https://www.statsmodels.org/devel/generated/statsmodels.stats.weightstats.ztest.html

In [24]:
_, p = ztest(data_h0, data_h1, value=h1_mean - h0_mean, alternative='larger')
p = 1 - p

if p < alpha:
    print('Reject null hypothesis (H0)')
    print('Accepting alternative hypothesis (H1)')
else:
    print('Reject alternative hypothesis (H1)')
    print('Continuing with null hypothesis (H0)')

Reject null hypothesis (H0)
Accepting alternative hypothesis (H1)


## T studant distribution

In [29]:
data_t_h0 = np.array([149. , 160., 147., 189., 175., 168., 156., 160., 152.])
data_t_h0

array([149., 160., 147., 189., 175., 168., 156., 160., 152.])

In [28]:
data_t_h1 = data_t_h0 * 1.03
data_t_h1

array([153.47, 164.8 , 151.41, 194.67, 180.25, 173.04, 160.68, 164.8 ,
       156.56])

In [39]:
_, p = ttest_rel(data_t_h0, data_t_h1)
p

4.072922493930081e-10

In [40]:
alpha = 0.01

if p < alpha:
    print('Reject null hypothesis (H0)')
    print('Accepting alternative hypothesis (H1)')
else:
    print('Reject alternative hypothesis (H1)')
    print('Continuing with null hypothesis (H0)')

Reject null hypothesis (H0)
Accepting alternative hypothesis (H1)
